/*
 * Copyright (C) 2026 Romain Viallard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

// NOLINTBEGIN

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum Key : uint8_t {
  KeyUnknown = 0,
  KeyReturn,
  KeyEscape,
  KeyBackspace,
  KeyTab,
  KeySpace,
  KeyExclaim,
  KeyDblApostrophe,
  KeyHash,
  KeyDollar,
  KeyPercent,
  KeyAmpersand,
  KeyApostrophe,
  KeyLeftParen,
  KeyRightParen,
  KeyAsterisk,
  KeyPlus,
  KeyComma,
  KeyMinus,
  KeyPeriod,
  KeySlash,
  KeyDigit0,
  KeyDigit1,
  KeyDigit2,
  KeyDigit3,
  KeyDigit4,
  KeyDigit5,
  KeyDigit6,
  KeyDigit7,
  KeyDigit8,
  KeyDigit9,
  KeyColon,
  KeySemicolon,
  KeyLess,
  KeyEquals,
  KeyGreater,
  KeyQuestion,
  KeyAt,
  KeyLeftBracket,
  KeyBackslash,
  KeyRightBracket,
  KeyCaret,
  KeyUnderscore,
  KeyGrave,
  KeyA,
  KeyB,
  KeyC,
  KeyD,
  KeyE,
  KeyF,
  KeyG,
  KeyH,
  KeyI,
  KeyJ,
  KeyK,
  KeyL,
  KeyM,
  KeyN,
  KeyO,
  KeyP,
  KeyQ,
  KeyR,
  KeyS,
  KeyT,
  KeyU,
  KeyV,
  KeyW,
  KeyX,
  KeyY,
  KeyZ,
  KeyLeftBrace,
  KeyPipe,
  KeyRightBrace,
  KeyTilde,
  KeyDelete,
  KeyPlusMinus,
  KeyF1,
  KeyF2,
  KeyF3,
  KeyF4,
  KeyF5,
  KeyF6,
  KeyF7,
  KeyF8,
  KeyF9,
  KeyF10,
  KeyF11,
  KeyF12,
  KeyF13,
  KeyF14,
  KeyF15,
  KeyF16,
  KeyF17,
  KeyF18,
  KeyF19,
  KeyF20,
  KeyF21,
  KeyF22,
  KeyF23,
  KeyF24,
  KeyCapsLock,
  KeyPrintScreen,
  KeyScrollLock,
  KeyPause,
  KeyInsert,
  KeyHome,
  KeyPageUp,
  KeyEnd,
  KeyPageDown,
  KeyRight,
  KeyLeft,
  KeyDown,
  KeyUp,
  KeyNumLockClear,
  KeyApplication,
  KeyPower,
  KeyExecute,
  KeyHelp,
  KeyMenu,
  KeySelect,
  KeyStop,
  KeyAgain,
  KeyUndo,
  KeyCut,
  KeyCopy,
  KeyPaste,
  KeyFind,
  KeyAltErase,
  KeySysReq,
  KeyCancel,
  KeyClear,
  KeyPrior,
  KeyReturn2,
  KeySeparator,
  KeyOut,
  KeyOper,
  KeyClearAgain,
  KeyCrSel,
  KeyExSel,
  KeyKp0,
  KeyKp1,
  KeyKp2,
  KeyKp3,
  KeyKp4,
  KeyKp5,
  KeyKp6,
  KeyKp7,
  KeyKp8,
  KeyKp9,
  KeyKpDivide,
  KeyKpMultiply,
  KeyKpMinus,
  KeyKpPlus,
  KeyKpEnter,
  KeyKpPeriod,
  KeyKpEquals,
  KeyKpComma,
  KeyKp00,
  KeyKp000,
  KeyKpEqualsAs400,
  KeyThousandsSeparator,
  KeyDecimalSeparator,
  KeyCurrencyUnit,
  KeyCurrencySubunit,
  KeyKpLeftParen,
  KeyKpRightParen,
  KeyKpLeftBrace,
  KeyKpRightBrace,
  KeyKpTab,
  KeyKpBackspace,
  KeyKpA,
  KeyKpB,
  KeyKpC,
  KeyKpD,
  KeyKpE,
  KeyKpF,
  KeyKpXor,
  KeyKpPower,
  KeyKpPercent,
  KeyKpLess,
  KeyKpGreater,
  KeyKpAmpersand,
  KeyKpDblAmpersand,
  KeyKpVerticalBar,
  KeyKpDblVerticalBar,
  KeyKpColon,
  KeyKpHash,
  KeyKpSpace,
  KeyKpAt,
  KeyKpExclam,
  KeyKpMemStore,
  KeyKpMemRecall,
  KeyKpMemClear,
  KeyKpMemAdd,
  KeyKpMemSubtract,
  KeyKpMemMultiply,
  KeyKpMemDivide,
  KeyKpPlusMinus,
  KeyKpClear,
  KeyKpClearEntry,
  KeyKpBinary,
  KeyKpOctal,
  KeyKpDecimal,
  KeyKpHexadecimal,
  KeyLeftCtrl,
  KeyLeftShift,
  KeyLeftAlt,
  KeyLeftGui,
  KeyRightCtrl,
  KeyRightShift,
  KeyRightAlt,
  KeyRightGui,
  KeyMode,
  KeySleep,
  KeyWake,
  KeyChannelIncrement,
  KeyChannelDecrement,
  KeyMediaPlay,
  KeyMediaPause,
  KeyMediaRecord,
  KeyMediaFastForward,
  KeyMediaRewind,
  KeyMediaNextTrack,
  KeyMediaPreviousTrack,
  KeyMediaStop,
  KeyMediaEject,
  KeyMediaPlayPause,
  KeyMediaSelect,
  KeyMute,
  KeyVolumeUp,
  KeyVolumeDown,
  KeyAcNew,
  KeyAcOpen,
  KeyAcClose,
  KeyAcExit,
  KeyAcSave,
  KeyAcPrint,
  KeyAcProperties,
  KeyAcSearch,
  KeyAcHome,
  KeyAcBack,
  KeyAcForward,
  KeyAcStop,
  KeyAcRefresh,
  KeyAcBookmarks,
  KeySoftLeft,
  KeySoftRight,
  KeyCall,
  KeyEndCall,
  KeyLeftTab,
  KeyLevel5Shift,
  KeyMultiKeyCompose,
  KeyLeftMeta,
  KeyRightMeta,
  KeyLeftHyper,
  KeyRightHyper,
} Key;

typedef enum Scancode : uint8_t {
  ScancodeUnknown = 0,
  ScancodeA,
  ScancodeB,
  ScancodeC,
  ScancodeD,
  ScancodeE,
  ScancodeF,
  ScancodeG,
  ScancodeH,
  ScancodeI,
  ScancodeJ,
  ScancodeK,
  ScancodeL,
  ScancodeM,
  ScancodeN,
  ScancodeO,
  ScancodeP,
  ScancodeQ,
  ScancodeR,
  ScancodeS,
  ScancodeT,
  ScancodeU,
  ScancodeV,
  ScancodeW,
  ScancodeX,
  ScancodeY,
  ScancodeZ,
  ScancodeDigit1,
  ScancodeDigit2,
  ScancodeDigit3,
  ScancodeDigit4,
  ScancodeDigit5,
  ScancodeDigit6,
  ScancodeDigit7,
  ScancodeDigit8,
  ScancodeDigit9,
  ScancodeDigit0,
  ScancodeReturn,
  ScancodeEscape,
  ScancodeBackspace,
  ScancodeTab,
  ScancodeSpace,
  ScancodeMinus,
  ScancodeEquals,
  ScancodeLeftBracket,
  ScancodeRightBracket,
  ScancodeBackslash,
  ScancodeNonUsHash,
  ScancodeSemicolon,
  ScancodeApostrophe,
  ScancodeGrave,
  ScancodeComma,
  ScancodePeriod,
  ScancodeSlash,
  ScancodeCapsLock,
  ScancodeF1,
  ScancodeF2,
  ScancodeF3,
  ScancodeF4,
  ScancodeF5,
  ScancodeF6,
  ScancodeF7,
  ScancodeF8,
  ScancodeF9,
  ScancodeF10,
  ScancodeF11,
  ScancodeF12,
  ScancodeF13,
  ScancodeF14,
  ScancodeF15,
  ScancodeF16,
  ScancodeF17,
  ScancodeF18,
  ScancodeF19,
  ScancodeF20,
  ScancodeF21,
  ScancodeF22,
  ScancodeF23,
  ScancodeF24,
  ScancodePrintScreen,
  ScancodeScrollLock,
  ScancodePause,
  ScancodeInsert,
  ScancodeHome,
  ScancodePageUp,
  ScancodeDelete,
  ScancodeEnd,
  ScancodePageDown,
  ScancodeRight,
  ScancodeLeft,
  ScancodeDown,
  ScancodeUp,
  ScancodeNumLockClear,
  ScancodeKpDivide,
  ScancodeKpMultiply,
  ScancodeKpMinus,
  ScancodeKpPlus,
  ScancodeKpEnter,
  ScancodeKp1,
  ScancodeKp2,
  ScancodeKp3,
  ScancodeKp4,
  ScancodeKp5,
  ScancodeKp6,
  ScancodeKp7,
  ScancodeKp8,
  ScancodeKp9,
  ScancodeKp0,
  ScancodeKpPeriod,
  ScancodeKpEquals,
  ScancodeKpComma,
  ScancodeKpEqualsAs400,
  ScancodeKp00,
  ScancodeKp000,
  ScancodeKpLeftParen,
  ScancodeKpRightParen,
  ScancodeKpLeftBrace,
  ScancodeKpRightBrace,
  ScancodeKpTab,
  ScancodeKpBackspace,
  ScancodeKpA,
  ScancodeKpB,
  ScancodeKpC,
  ScancodeKpD,
  ScancodeKpE,
  ScancodeKpF,
  ScancodeKpXor,
  ScancodeKpPower,
  ScancodeKpPercent,
  ScancodeKpLess,
  ScancodeKpGreater,
  ScancodeKpAmpersand,
  ScancodeKpDblAmpersand,
  ScancodeKpVerticalBar,
  ScancodeKpDblVerticalBar,
  ScancodeKpColon,
  ScancodeKpHash,
  ScancodeKpSpace,
  ScancodeKpAt,
  ScancodeKpExclam,
  ScancodeKpMemStore,
  ScancodeKpMemRecall,
  ScancodeKpMemClear,
  ScancodeKpMemAdd,
  ScancodeKpMemSubtract,
  ScancodeKpMemMultiply,
  ScancodeKpMemDivide,
  ScancodeKpPlusMinus,
  ScancodeKpClear,
  ScancodeKpClearEntry,
  ScancodeKpBinary,
  ScancodeKpOctal,
  ScancodeKpDecimal,
  ScancodeKpHexadecimal,
  ScancodeNonUsBackslash,
  ScancodeInternational1,
  ScancodeInternational2,
  ScancodeInternational3,
  ScancodeInternational4,
  ScancodeInternational5,
  ScancodeInternational6,
  ScancodeInternational7,
  ScancodeInternational8,
  ScancodeInternational9,
  ScancodeLang1,
  ScancodeLang2,
  ScancodeLang3,
  ScancodeLang4,
  ScancodeLang5,
  ScancodeLang6,
  ScancodeLang7,
  ScancodeLang8,
  ScancodeLang9,
  ScancodeApplication,
  ScancodePower,
  ScancodeExecute,
  ScancodeHelp,
  ScancodeMenu,
  ScancodeSelect,
  ScancodeStop,
  ScancodeAgain,
  ScancodeUndo,
  ScancodeCut,
  ScancodeCopy,
  ScancodePaste,
  ScancodeFind,
  ScancodeMute,
  ScancodeVolumeUp,
  ScancodeVolumeDown,
  ScancodeAltErase,
  ScancodeSysReq,
  ScancodeCancel,
  ScancodeClear,
  ScancodePrior,
  ScancodeReturn2,
  ScancodeSeparator,
  ScancodeOut,
  ScancodeOper,
  ScancodeClearAgain,
  ScancodeCrSel,
  ScancodeExSel,
  ScancodeThousandsSeparator,
  ScancodeDecimalSeparator,
  ScancodeCurrencyUnit,
  ScancodeCurrencySubunit,
  ScancodeLeftCtrl,
  ScancodeLeftShift,
  ScancodeLeftAlt,
  ScancodeLeftGui,
  ScancodeRightCtrl,
  ScancodeRightShift,
  ScancodeRightAlt,
  ScancodeRightGui,
  ScancodeMode,
  ScancodeSleep,
  ScancodeWake,
  ScancodeChannelIncrement,
  ScancodeChannelDecrement,
  ScancodeMediaPlay,
  ScancodeMediaPause,
  ScancodeMediaRecord,
  ScancodeMediaFastForward,
  ScancodeMediaRewind,
  ScancodeMediaNextTrack,
  ScancodeMediaPreviousTrack,
  ScancodeMediaStop,
  ScancodeMediaEject,
  ScancodeMediaPlayPause,
  ScancodeMediaSelect,
  ScancodeAcNew,
  ScancodeAcOpen,
  ScancodeAcClose,
  ScancodeAcExit,
  ScancodeAcSave,
  ScancodeAcPrint,
  ScancodeAcProperties,
  ScancodeAcSearch,
  ScancodeAcHome,
  ScancodeAcBack,
  ScancodeAcForward,
  ScancodeAcStop,
  ScancodeAcRefresh,
  ScancodeAcBookmarks,
  ScancodeSoftLeft,
  ScancodeSoftRight,
  ScancodeCall,
  ScancodeEndCall,
} Scancode;

typedef enum idunn_platform_event_type : uint8_t {
  QuitEvent = 0,
  KeyEvent,
  ScancodeEvent,
} idunn_platform_event_type;

typedef struct idunn_platform_key_event {
  Key key;
  bool value;
} idunn_platform_key_event;

typedef struct idunn_platform_scancode_event {
  Scancode scancode;
  bool value;
} idunn_platform_scancode_event;

typedef struct idunn_platform_event {
  idunn_platform_event_type type;
  union {
    idunn_platform_key_event key;
    idunn_platform_scancode_event scancode;
  } payload;
} idunn_platform_event;

typedef struct idunn_platform_config {
  float *pDeltaTime;
  uint32_t *pEventCount;
  idunn_platform_event **ppEvent;
} idunn_platform_config;

void idunn_platform_init(idunn_platform_config *config, void **pPlatform);
void idunn_platform_uninit(void *platform);
void idunn_platform_tick(void *platform);
void idunn_platform_key_subscribe(void *platform, Key key);
void idunn_platform_key_unsubscribe(void *platform, Key key);
void idunn_platform_scancode_subscribe(void *platform, Scancode scancode);
void idunn_platform_scancode_unsubscribe(void *platform, Scancode scancode);

typedef struct idunn_window_config {
  void *platform;
  const char *title;
  uint32_t width;
  uint32_t height;
  void **window;
} idunn_window_config;

void idunn_platform_window_init(idunn_window_config *config, void **pWindow);
void idunn_platform_window_uninit(void *window);

#ifdef __cplusplus
}
#endif

// NOLINTEND
