header:
  license:
    spdx-id: AGPL-3.0-or-later
    copyright-owner: Romain Viallard
    copyright-year: 2026

  paths-ignore:
    - '.clangd'
    - '.clang-format'
    - '.clang-tidy'
    - '.direnv'
    - '.envrc'
    - '.gitignore'
    - '.gitmodules'
    - '.licenserc.yaml'
    - 'dist-newstyle'
    - 'idunn.cabal'
    - 'Justfile'
    - 'LICENSE'
    - 'vendor'
    - '**/*.lock'
    - '**/*.md'
    - '**/*.nix'

  comment: on-failure

  language:
    Slang:
      extensions:
        - ".slang"
      comment_style_id: SlashAsterisk
