header:
  license:
    spdx-id: AGPL-3.0-or-later
    copyright-owner: Romain Viallard
    copyright-year: 2026

  paths-ignore:
    - '.clangd'
    - '.direnv'
    - '.envrc'
    - '.gitignore'
    - '.licenserc.yaml'
    - 'dist-newstyle'
    - 'idunn.cabal'
    - 'Justfile'
    - 'LICENSE'
    - '**/*.lock'
    - '**/*.md'
    - '**/*.nix'

  comment: on-failure
